### ISSUE TITLE
Cannot X out of MacroMenu

### ISSUE THREAD

**Issue by GudBoiNero** [GudBoiNero/PrimedKeys#22]
Can't exit out of menu.
![image](https://github.com/GudBoiNero/PrimedKeys/assets/80719767/9de32e96-baa9-4c61-bfaf-f72ea3cc3c59)
It should close the menu and shut off the program.

**Comment by rjwignar** [comment]
I would like to look into this.
Please assign the issue to me.

**Comment by rjwignar** [comment]
I think I've got something figured out.
I'll have a PR ready tomorrow

**Comment by GudBoiNero** [comment]
Thanks @rjwignar! I appreciate the help! I'm going to be doing some more with the project shortly. Was just taking a week or two long break since I was busy with some things.

**Comment by rjwignar** [comment]
The pleasure's mine - you've got a cool project! 
Can't wait to see how it turns out.

My Pull Request is now ready. Apologies for the delay.
